// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SemanticInventory.Backend.Data;

#nullable disable

namespace SemanticInventory.Backend.Migrations
{
    [DbContext(typeof(SemanticInventoryContext))]
    [Migration("20260331161551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SemanticInventory.Backend.Data.Inventory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("SemanticInventory.Backend.Data.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("SemanticInventory.Backend.Data.ItemEmbedding", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("E0")
                        .HasColumnType("REAL");

                    b.Property<float>("E1")
                        .HasColumnType("REAL");

                    b.Property<float>("E2")
                        .HasColumnType("REAL");

                    b.HasKey("ItemId");

                    b.ToTable("ItemEmbeddings", (string)null);
                });

            modelBuilder.Entity("SemanticInventory.Backend.Data.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OccurredUtc");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("SemanticInventory.Backend.Data.Inventory", b =>
                {
                    b.HasOne("SemanticInventory.Backend.Data.Item", "Item")
                        .WithOne("Inventory")
                        .HasForeignKey("SemanticInventory.Backend.Data.Inventory", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SemanticInventory.Backend.Data.ItemEmbedding", b =>
                {
                    b.HasOne("SemanticInventory.Backend.Data.Item", "Item")
                        .WithOne("Embedding")
                        .HasForeignKey("SemanticInventory.Backend.Data.ItemEmbedding", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SemanticInventory.Backend.Data.Sale", b =>
                {
                    b.HasOne("SemanticInventory.Backend.Data.Item", "Item")
                        .WithMany("Sales")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SemanticInventory.Backend.Data.Item", b =>
                {
                    b.Navigation("Embedding");

                    b.Navigation("Inventory");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
